module.exports = {
  extends: ['plugin:prettier/recommended'],
  rules: {
    'prettier/prettier': [
      'error',
      {
        semi: false,
        singleQuote: true,
        tabWidth: 2,
        printWidth: 100,
        useTabs: false,
        jsxSingleQuote: false,
        bracketSpacing: true,
        jsxBracketSameLine: false,
        arrowParens: 'always',
        proseWrap: 'preserve',
        htmlWhitespaceSensitivity: 'css',
        endOfLine: 'lf',
        trailingComma: 'all',
      },
    ],
    semi: ['error', 'never'],
    'template-curly-spacing': 'off',
    'object-curly-spacing': ['error', 'always'],
    'switch-colon-spacing': ['error', { after: true, before: false }],
    // 和 perttier 的冲突
    // 'array-bracket-spacing': ['error', 'always', { singleValue: false }],
    complexity: ['error', 100],
    'no-param-reassign': 0,
    'no-extend-native': 0,
    'no-script-url': 0,
    'no-proto': 'error',
    quotes: ['error', 'single'],
    'key-spacing': ['error', { beforeColon: false, afterColon: true }],
    'comma-dangle': [
      'error',
      {
        arrays: 'always-multiline',
        objects: 'always-multiline',
        imports: 'always-multiline',
        exports: 'always-multiline',
        functions: 'ignore',
      },
    ],
    'no-void': ['error'],
  },
}
